### PR TITLE
Provide a fix for issue #126

### PR DESCRIPTION
**Pull request by Zabamund**
In the __init__ method, all `TypeError` instances were ignored as
they were assumed to be catching instances of `None`. They were
also catching instances of `tuples` though and here I suggest
being explicit about catching the instances of `None` and adding
other valid objects in the same way as for `ValueError` instances.

### CODE REVIEW

**Comment by kwinkunks** [comment]
Awesome! Please can you add a couple of tests for this?

**Comment by Zabamund** [comment]
Yep in the process of writing tests right now :-)

**Comment by kwinkunks** [comment]
Okay, please add the commit to this PR, I think that should be possible

**Comment by Zabamund** [comment]
I'm not sure how to fix this as before my commit, coverage was at 75.254% and it's now higher at 75.423%.
The two tests I added cover the code I added, namely checking for None and for tuples in the initialisation of a Component.
Any suggestions?

**Comment by Zabamund** [comment]
thank you for merging despite that failed coverage Matt :+1:

**Pull request merged**
